### ISSUE TITLE
WARN seems a bit much for a missing component

### ISSUE THREAD

**Issue by elgreg** [clay/amphora-amp#7]
Lots of components aren't allowed in AMP  and our logs are full of warnings about them every time someone looks at a page. Is it OK to just change 'warn' to 'debug' here? https://github.com/clay/amphora-amp/blob/57e2e30b7aa6599b15fb5d204eeb98d47d791124/lib/util.js#L26

**Comment by jonwinton** [comment]
Would it make sense for it to be `debug`? I'm thinking you'd only go looking for missing templates when debugging why something wasn't included. And it would make warnings/errors more meaningful for things like deprecation warnings/app issues

**Comment by yuliyv** [comment]
I can turn this into a configuration for the module so that you can set what the log level of this message will be if that will help

**Comment by elgreg** [comment]
Oh sorry. Yes. Meant we should tone it down to with info or debug. I think debug is fine. No need for config. I would just bump the log level if I want to know more.
